matrix:
  include:
    - language: go
      before_script:
        - cd backend
        - go get github.com/gorilla/mux
      script:
        - cd data
        - go test -v 
        - cd ..\test
        - go test -v

    - language: node_js
      before_script:
        - cd frontend
        - npm install
      script:
        - npm run test:unit
        - npm run lint
