version: '3'

services:
  backend:
    depends_on:
      - db
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      CONNECTION: addressbook:SuperSecretPassword@tcp(db:3306)/addressbook

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always

  proxy:
    depends_on:
      - backend
      - frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"

  db:
     image: mysql:latest
     restart: always
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: "yes" 
       MYSQL_DATABASE: addressbook
       MYSQL_USER: addressbook
       MYSQL_PASSWORD: SuperSecretPassword


